# -*- coding: utf-8 -*-
"""scam2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fKfb8UD4u6aYRRfDD1h0A0BkD86MkWYn
"""

# Import necessary libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# Data preprocessing
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.impute import SimpleImputer
from sklearn.decomposition import PCA

# Unsupervised learning models
from sklearn.cluster import DBSCAN, KMeans, AgglomerativeClustering
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.svm import OneClassSVM
from sklearn.mixture import GaussianMixture

# Evaluation metrics
from sklearn.metrics import silhouette_score, calinski_harabasz_score, davies_bouldin_score

print("Libraries imported successfully!")

# Load the dataset (adjust path if needed)
# If you uploaded directly to Colab, use:
df = pd.read_csv('/content/synthetic_bank_transactions_india.csv')

# If in Google Drive, use:
# df = pd.read_csv('/content/drive/MyDrive/synthetic_bank_transactions_india.csv')

print("Dataset shape:", df.shape)
print("\nFirst 5 rows:")
df.head()

# Check basic info
print("Dataset Info:")
df.info()

print("\n" + "="*50)
print("Missing Values:")
print(df.isnull().sum())

print("\n" + "="*50)
print("Duplicate Check:")
print(f"Duplicate rows: {df.duplicated().sum()}")

print("\n" + "="*50)
print("Basic Statistics:")
df.describe(include='all')

# Make a copy of the original dataframe
df_clean = df.copy()

# Check for missing values
print("Missing values before cleaning:")
print(df_clean.isnull().sum())

# Handle missing values
# For categorical columns, fill with mode
categorical_cols = df_clean.select_dtypes(include=['object']).columns
for col in categorical_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].mode()[0], inplace=True)

# For numerical columns (if any), fill with median
numerical_cols = df_clean.select_dtypes(include=[np.number]).columns
for col in numerical_cols:
    if df_clean[col].isnull().sum() > 0:
        df_clean[col].fillna(df_clean[col].median(), inplace=True)

# Remove duplicates
df_clean.drop_duplicates(inplace=True)

print("\n" + "="*50)
print("Missing values after cleaning:")
print(df_clean.isnull().sum())

print(f"\nShape after cleaning: {df_clean.shape}")

# Extract useful features from transaction_narration
def extract_transaction_features(df):
    df = df.copy()

    # Extract transaction type
    df['transaction_type'] = df['transaction_narration'].str.extract(r'(UPI|IMPS|NEFT|Net Banking|Mobile Banking|Debit Card|ATM Withdrawal)')

    # Extract merchant/platform
    df['merchant'] = df['transaction_narration'].str.extract(r'(Amazon|Flipkart|Zomato|Swiggy|Uber|IRCTC|Electricity Bill|Rent Payment)')

    # Extract amount
    df['amount'] = df['transaction_narration'].str.extract(r'INR\s*(\d+)').astype(float)

    return df

df_clean = extract_transaction_features(df_clean)

print("Feature extraction completed!")
print(f"New columns added: {[col for col in df_clean.columns if col not in df.columns]}")
df_clean.head()

# Create aggregated features per account (as per your PPT - velocity metrics, device sharing, etc.)
account_features = df_clean.groupby('account_number').agg({
    'amount': ['count', 'sum', 'mean', 'std', 'max', 'min'],
    'transaction_type': lambda x: x.nunique(),
    'merchant': lambda x: x.nunique(),
    'name': 'first',
    'account_type': 'first',
    'account_product': 'first'
}).reset_index()

# Flatten column names
account_features.columns = ['account_number', 'transaction_count', 'total_amount',
                           'avg_amount', 'std_amount', 'max_amount', 'min_amount',
                           'unique_transaction_types', 'unique_merchants',
                           'name', 'account_type', 'account_product']

# Fill NaN values in std_amount (for accounts with single transaction)
account_features['std_amount'].fillna(0, inplace=True)

# Calculate velocity metrics
account_features['amount_range'] = account_features['max_amount'] - account_features['min_amount']
account_features['amount_variation'] = account_features['std_amount'] / (account_features['avg_amount'] + 1)

print(f"Account-level features shape: {account_features.shape}")
account_features.head()

# Create multi-channel indicators (as per your PPT - App, Web, ATM, UPI)
channel_mapping = {
    'UPI': 'Mobile',
    'IMPS': 'Mobile',
    'NEFT': 'Web',
    'Net Banking': 'Web',
    'Mobile Banking': 'Mobile',
    'Debit Card': 'ATM',
    'ATM Withdrawal': 'ATM'
}

df_clean['channel'] = df_clean['transaction_type'].map(channel_mapping)

# Count transactions per channel for each account
channel_counts = pd.crosstab(df_clean['account_number'], df_clean['channel']).reset_index()
channel_counts.columns = ['account_number'] + [f'{col.lower()}_count' for col in channel_counts.columns if col != 'account_number']

# Merge with account features
account_features = account_features.merge(channel_counts, on='account_number', how='left')
account_features.fillna(0, inplace=True)

# Calculate multi-channel diversity
account_features['channel_diversity'] = account_features[['atm_count', 'mobile_count', 'web_count']].sum(axis=1)
account_features['is_multi_channel'] = (account_features['channel_diversity'] > 1).astype(int)

print("Multi-channel features added!")
account_features.head()

# Since we don't have actual device/IP data in the CSV, we'll simulate based on patterns
# This simulates the "Shared Device Detection" and "IP Addresses" from your PPT

np.random.seed(42)

# Simulate device IDs (some accounts share devices)
def simulate_device_sharing(account_features):
    n_accounts = len(account_features)
    n_devices = n_accounts // 3  # Each device used by ~3 accounts on average

    # Create device assignments with some sharing
    device_probs = np.random.dirichlet(np.ones(n_devices) * 0.5)
    device_assignments = np.random.choice(n_devices, size=n_accounts, p=device_probs)

    account_features['device_id'] = device_assignments

    # Calculate accounts per device
    device_counts = account_features['device_id'].value_counts().to_dict()
    account_features['accounts_per_device'] = account_features['device_id'].map(device_counts)
    account_features['is_shared_device'] = (account_features['accounts_per_device'] > 1).astype(int)

    return account_features

# Simulate IP addresses (geographic diversity)
def simulate_ip_features(account_features):
    n_accounts = len(account_features)

    # Simulate IP change frequency
    account_features['ip_change_frequency'] = np.random.randint(1, 20, size=n_accounts)

    # Simulate suspicious IP indicators
    account_features['is_suspicious_ip'] = np.random.choice([0, 1], size=n_accounts, p=[0.9, 0.1])

    return account_features

account_features = simulate_device_sharing(account_features)
account_features = simulate_ip_features(account_features)

print("Device and IP simulation features added!")
account_features[['account_number', 'device_id', 'accounts_per_device',
                 'is_shared_device', 'ip_change_frequency', 'is_suspicious_ip']].head()

# Create features that simulate graph-based intelligence (as per your PPT)
# These represent relationship strength, cluster risk, etc.

def create_graph_features(account_features):
    df = account_features.copy()

    # Simulate transaction velocity (multi-hop transfers)
    df['velocity_score'] = (df['transaction_count'] * df['avg_amount'] / 10000).clip(0, 100)

    # Simulate degree centrality (connected accounts)
    df['degree_centrality'] = np.random.uniform(0, 1, size=len(df))

    # Simulate cluster risk
    df['cluster_risk_score'] = np.random.uniform(0, 100, size=len(df))

    # Simulate jurisdiction risk
    jurisdiction_risk = {'Savings': 30, 'Current': 50, 'NRI': 70, 'Business': 60, 'Salary': 40}
    df['jurisdiction_risk'] = df['account_type'].map(jurisdiction_risk).fillna(50)

    # Combined risk indicators
    df['suspicious_velocity'] = (df['velocity_score'] > 70).astype(int)
    df['high_centrality'] = (df['degree_centrality'] > 0.7).astype(int)
    df['high_cluster_risk'] = (df['cluster_risk_score'] > 70).astype(int)

    return df

account_features = create_graph_features(account_features)

print("Graph intelligence features created!")
print(f"Final feature set has {account_features.shape[1]} columns")
account_features.head()

# Select features for model training
feature_columns = [
    'transaction_count', 'total_amount', 'avg_amount', 'std_amount',
    'max_amount', 'min_amount', 'amount_range', 'amount_variation',
    'unique_transaction_types', 'unique_merchants', 'atm_count',
    'mobile_count', 'web_count', 'channel_diversity', 'is_multi_channel',
    'accounts_per_device', 'is_shared_device', 'ip_change_frequency',
    'is_suspicious_ip', 'velocity_score', 'degree_centrality',
    'cluster_risk_score', 'jurisdiction_risk', 'suspicious_velocity',
    'high_centrality', 'high_cluster_risk'
]

# Ensure all selected columns exist
feature_columns = [col for col in feature_columns if col in account_features.columns]

X = account_features[feature_columns].copy()

# Handle any remaining infinite values
X = X.replace([np.inf, -np.inf], np.nan)
X = X.fillna(X.median())

print(f"Feature matrix shape: {X.shape}")
print(f"Features used: {feature_columns}")

# Standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled = pd.DataFrame(X_scaled, columns=feature_columns)

print("Features scaled successfully!")
print(f"Scaled data shape: {X_scaled.shape}")
print("\nFirst few rows of scaled data:")
X_scaled.head()

# Apply PCA for visualization
pca = PCA(n_components=2)
X_pca = pca.fit_transform(X_scaled)

print(f"Explained variance ratio: {pca.explained_variance_ratio_}")
print(f"Total explained variance: {sum(pca.explained_variance_ratio_):.3f}")

# Create DataFrame for plotting
pca_df = pd.DataFrame(X_pca, columns=['PC1', 'PC2'])
pca_df['account_number'] = account_features['account_number'].values

plt.figure(figsize=(10, 8))
plt.scatter(pca_df['PC1'], pca_df['PC2'], alpha=0.6, s=10)
plt.xlabel('First Principal Component')
plt.ylabel('Second Principal Component')
plt.title('PCA Visualization of Account Features')
plt.grid(True, alpha=0.3)
plt.show()

# Isolation Forest for anomaly detection
iso_forest = IsolationForest(contamination=0.1, random_state=42, n_estimators=200)
iso_forest.fit(X_scaled)

# Predict anomalies (-1 for anomalies, 1 for normal)
iso_forest_pred = iso_forest.predict(X_scaled)
iso_forest_scores = iso_forest.score_samples(X_scaled)

# Convert to binary labels (1 for anomaly, 0 for normal)
iso_forest_labels = (iso_forest_pred == -1).astype(int)

print("Isolation Forest Results:")
print(f"Anomalies detected: {sum(iso_forest_labels)} ({sum(iso_forest_labels)/len(iso_forest_labels)*100:.2f}%)")
print(f"Normal accounts: {len(iso_forest_labels) - sum(iso_forest_labels)}")

# Add results to dataframe
account_features['iso_forest_anomaly'] = iso_forest_labels
account_features['iso_forest_score'] = iso_forest_scores

# DBSCAN for density-based clustering
# Tune eps and min_samples for optimal clustering
eps_values = np.arange(0.5, 3.0, 0.5)
silhouette_scores = []

for eps in eps_values:
    dbscan = DBSCAN(eps=eps, min_samples=5)
    labels = dbscan.fit_predict(X_scaled)
    if len(set(labels)) > 1 and -1 not in set(labels):
        score = silhouette_score(X_scaled, labels)
        silhouette_scores.append(score)
    else:
        silhouette_scores.append(-1)

best_eps = eps_values[np.argmax(silhouette_scores)]
print(f"Best eps: {best_eps}")

# Run DBSCAN with best parameters
dbscan = DBSCAN(eps=best_eps, min_samples=5)
dbscan_labels = dbscan.fit_predict(X_scaled)

# Count clusters (excluding noise points labeled -1)
n_clusters = len(set(dbscan_labels)) - (1 if -1 in dbscan_labels else 0)
n_noise = list(dbscan_labels).count(-1)

print(f"\nDBSCAN Results:")
print(f"Number of clusters: {n_clusters}")
print(f"Noise points (potential anomalies): {n_noise} ({n_noise/len(dbscan_labels)*100:.2f}%)")

account_features['dbscan_cluster'] = dbscan_labels
account_features['dbscan_is_noise'] = (dbscan_labels == -1).astype(int)

# Gaussian Mixture Model for probabilistic clustering
gmm = GaussianMixture(n_components=5, random_state=42, covariance_type='full')
gmm_labels = gmm.fit_predict(X_scaled)
gmm_probs = gmm.predict_proba(X_scaled)

# Identify potential anomalies (low probability assignments)
gmm_anomaly_scores = -gmm.score_samples(X_scaled)
threshold = np.percentile(gmm_anomaly_scores, 90)  # Top 10% as anomalies
gmm_anomalies = (gmm_anomaly_scores > threshold).astype(int)

print("Gaussian Mixture Model Results:")
print(f"Clusters formed: {len(np.unique(gmm_labels))}")
print(f"Potential anomalies: {sum(gmm_anomalies)} ({sum(gmm_anomalies)/len(gmm_anomalies)*100:.2f}%)")

account_features['gmm_cluster'] = gmm_labels
account_features['gmm_anomaly'] = gmm_anomalies
account_features['gmm_anomaly_score'] = gmm_anomaly_scores

# Local Outlier Factor for local density-based anomaly detection
lof = LocalOutlierFactor(n_neighbors=20, contamination=0.1)
lof_labels = lof.fit_predict(X_scaled)
lof_negative_outlier_factor = lof.negative_outlier_factor_

print("Local Outlier Factor Results:")
lof_anomalies = sum(lof_labels == -1)
print(f"Anomalies detected: {lof_anomalies} ({lof_anomalies/len(lof_labels)*100:.2f}%)")

account_features['lof_anomaly'] = (lof_labels == -1).astype(int)
account_features['lof_score'] = lof_negative_outlier_factor

# Combine multiple models for ensemble anomaly score
account_features['ensemble_anomaly_count'] = (
    account_features['iso_forest_anomaly'] +
    account_features['dbscan_is_noise'] +
    account_features['gmm_anomaly'] +
    account_features['lof_anomaly']
)

# Normalize scores from different models for ensemble
from sklearn.preprocessing import MinMaxScaler

# Create normalized scores
score_scaler = MinMaxScaler()
ensemble_features = account_features[['iso_forest_score', 'gmm_anomaly_score', 'lof_score']].copy()
ensemble_features['iso_forest_score_norm'] = score_scaler.fit_transform(ensemble_features[['iso_forest_score']])
ensemble_features['gmm_anomaly_score_norm'] = score_scaler.fit_transform(ensemble_features[['gmm_anomaly_score']])
ensemble_features['lof_score_norm'] = score_scaler.fit_transform(-ensemble_features[['lof_score']])  # LOF more negative = more anomalous

# Calculate ensemble score (0-100 scale as per your PPT)
account_features['risk_score_ensemble'] = (
    ensemble_features['iso_forest_score_norm'] * 0.3 +
    ensemble_features['gmm_anomaly_score_norm'] * 0.3 +
    ensemble_features['lof_score_norm'] * 0.4
) * 100

# Confidence based on model agreement
account_features['ensemble_confidence'] = (account_features['ensemble_anomaly_count'] / 4) * 100

print("Ensemble risk scores created!")
print(f"Risk score range: {account_features['risk_score_ensemble'].min():.2f} - {account_features['risk_score_ensemble'].max():.2f}")
print(f"Confidence range: {account_features['ensemble_confidence'].min():.2f} - {account_features['ensemble_confidence'].max():.2f}")

# Identify high-risk accounts based on ensemble score
risk_threshold = 70  # As per your PPT, 0-100 scale
high_risk_accounts = account_features[account_features['risk_score_ensemble'] > risk_threshold].copy()
high_risk_accounts = high_risk_accounts.sort_values('risk_score_ensemble', ascending=False)

print(f"High-risk accounts detected: {len(high_risk_accounts)} ({len(high_risk_accounts)/len(account_features)*100:.2f}%)")
print(f"\nTop 10 high-risk accounts:")
high_risk_accounts[['account_number', 'name', 'risk_score_ensemble', 'ensemble_confidence',
                    'ensemble_anomaly_count', 'velocity_score', 'cluster_risk_score']].head(10)

# Create visualization of risk scores and clusters
fig, axes = plt.subplots(2, 3, figsize=(18, 12))  # Fixed: figsize as tuple

# Risk score distribution
axes[0, 0].hist(account_features['risk_score_ensemble'], bins=50, edgecolor='black', alpha=0.7)
axes[0, 0].axvline(x=70, color='red', linestyle='--', label='High-risk threshold (70)')
axes[0, 0].set_xlabel('Risk Score')
axes[0, 0].set_ylabel('Frequency')
axes[0, 0].set_title('Distribution of Ensemble Risk Scores')
axes[0, 0].legend()
axes[0, 0].grid(True, alpha=0.3)

# PCA with risk scores
sc = axes[0, 1].scatter(pca_df['PC1'], pca_df['PC2'],
                         c=account_features['risk_score_ensemble'],
                         cmap='RdYlGn_r', s=20, alpha=0.6)
plt.colorbar(sc, ax=axes[0, 1], label='Risk Score')
axes[0, 1].set_xlabel('PC1')
axes[0, 1].set_ylabel('PC2')
axes[0, 1].set_title('PCA with Risk Scores')

# Model agreement
agreement_counts = account_features['ensemble_anomaly_count'].value_counts().sort_index()
# Ensure all values 0-4 are represented
all_counts = pd.Series([0, 1, 2, 3, 4], index=[0, 1, 2, 3, 4])
agreement_counts = agreement_counts.add(all_counts, fill_value=0).fillna(0)
axes[0, 2].bar(agreement_counts.index, agreement_counts.values, color='skyblue', edgecolor='black')
axes[0, 2].set_xlabel('Number of Models Flagging Anomaly')
axes[0, 2].set_ylabel('Number of Accounts')
axes[0, 2].set_title('Model Agreement on Anomalies')
axes[0, 2].set_xticks([0, 1, 2, 3, 4])
axes[0, 2].grid(True, alpha=0.3)

# Transaction count vs Risk Score
axes[1, 0].scatter(account_features['transaction_count'], account_features['risk_score_ensemble'],
                    alpha=0.6, c=account_features['ensemble_anomaly_count'], cmap='Reds', s=20)
axes[1, 0].set_xlabel('Transaction Count')
axes[1, 0].set_ylabel('Risk Score')
axes[1, 0].set_title('Transaction Count vs Risk Score')
axes[1, 0].grid(True, alpha=0.3)

# Velocity Score vs Cluster Risk
axes[1, 1].scatter(account_features['velocity_score'], account_features['cluster_risk_score'],
                    alpha=0.6, c=account_features['risk_score_ensemble'], cmap='RdYlGn_r', s=20)
axes[1, 1].set_xlabel('Velocity Score')
axes[1, 1].set_ylabel('Cluster Risk Score')
axes[1, 1].set_title('Velocity vs Cluster Risk')
axes[1, 1].grid(True, alpha=0.3)

# Channel diversity
channel_counts = account_features[['atm_count', 'mobile_count', 'web_count']].sum()
# Handle case where some channels might be missing
channel_labels = []
channel_values = []
for channel in ['atm_count', 'mobile_count', 'web_count']:
    if channel in channel_counts.index:
        channel_labels.append(channel.replace('_count', '').upper())
        channel_values.append(channel_counts[channel])

if sum(channel_values) > 0:
    axes[1, 2].pie(channel_values, labels=channel_labels, autopct='%1.1f%%', startangle=90)
else:
    axes[1, 2].text(0.5, 0.5, 'No channel data', ha='center', va='center')
axes[1, 2].set_title('Transaction Channel Distribution')

plt.tight_layout()
plt.show()

# Simulate mule ring detection based on shared devices and patterns
def detect_mule_rings(account_features, risk_threshold=70):
    high_risk = account_features[account_features['risk_score_ensemble'] > risk_threshold].copy()

    # Group by device to find potential mule rings
    device_rings = high_risk.groupby('device_id').agg({
        'account_number': list,
        'risk_score_ensemble': 'mean',
        'ensemble_confidence': 'mean',
        'transaction_count': 'sum',
        'total_amount': 'sum',
        'name': list
    }).reset_index()

    device_rings['ring_size'] = device_rings['account_number'].str.len()
    device_rings = device_rings[device_rings['ring_size'] > 1]  # Only rings with multiple accounts

    # Sort by risk
    device_rings = device_rings.sort_values('risk_score_ensemble', ascending=False)
    device_rings['ring_id'] = ['RING_' + str(i).zfill(3) for i in range(1, len(device_rings) + 1)]

    return device_rings

mule_rings = detect_mule_rings(account_features)

print(f"Detected {len(mule_rings)} potential mule rings!")
if len(mule_rings) > 0:
    print("\nTop mule rings by risk score:")
    display_cols = ['ring_id', 'ring_size', 'risk_score_ensemble', 'ensemble_confidence',
                   'transaction_count', 'total_amount']
    print(mule_rings[display_cols].head(10))
else:
    print("No mule rings detected with current threshold.")

# Create final output table as per your PPT
final_results = account_features[['account_number', 'name', 'account_type',
                                   'risk_score_ensemble', 'ensemble_confidence',
                                   'ensemble_anomaly_count', 'velocity_score',
                                   'cluster_risk_score', 'is_shared_device',
                                   'transaction_count', 'total_amount']].copy()

# Add reason codes (as per your PPT)
def generate_reason_codes(row):
    reasons = []
    if row['velocity_score'] > 70:
        reasons.append("High transaction velocity")
    if row['is_shared_device'] == 1:
        reasons.append("Shared device with multiple accounts")
    if row['cluster_risk_score'] > 70:
        reasons.append("Member of high-risk cluster")
    if row['ensemble_anomaly_count'] >= 3:
        reasons.append("Flagged by multiple detection models")
    if row['transaction_count'] > 10 and row['total_amount'] > 100000:
        reasons.append("Unusual transaction volume")

    return '; '.join(reasons) if reasons else "Normal activity"

final_results['reason_codes'] = final_results.apply(generate_reason_codes, axis=1)

# Add risk category
def risk_category(score):
    if score >= 80:
        return 'Critical'
    elif score >= 70:
        return 'High'
    elif score >= 50:
        return 'Medium'
    elif score >= 30:
        return 'Low'
    else:
        return 'Normal'

final_results['risk_category'] = final_results['risk_score_ensemble'].apply(risk_category)

# Sort by risk score
final_results = final_results.sort_values('risk_score_ensemble', ascending=False)

print("Final Risk Scoring Results:")
print(f"Total accounts analyzed: {len(final_results)}")
print(f"Critical risk accounts: {sum(final_results['risk_category'] == 'Critical')}")
print(f"High risk accounts: {sum(final_results['risk_category'] == 'High')}")
print(f"Medium risk accounts: {sum(final_results['risk_category'] == 'Medium')}")
print(f"Low risk accounts: {sum(final_results['risk_category'] == 'Low')}")
print(f"Normal accounts: {sum(final_results['risk_category'] == 'Normal')}")

print("\nTop 20 high-risk accounts:")
final_results.head(20)

# Save results to CSV
final_results.to_csv('mule_account_detection_results.csv', index=False)
account_features.to_csv('account_features_with_risk.csv', index=False)

# Save mule rings if detected
if len(mule_rings) > 0:
    mule_rings.to_csv('detected_mule_rings.csv', index=False)
    print("Mule rings saved to 'detected_mule_rings.csv'")

print("Results saved successfully!")

# Create summary statistics
summary_stats = pd.DataFrame({
    'Metric': ['Total Accounts', 'High-Risk Accounts (>70)', 'Critical Risk (>80)',
               'Avg Risk Score', 'Avg Confidence', 'Mule Rings Detected'],
    'Value': [
        len(final_results),
        sum(final_results['risk_score_ensemble'] > 70),
        sum(final_results['risk_score_ensemble'] > 80),
        f"{final_results['risk_score_ensemble'].mean():.2f}",
        f"{final_results['ensemble_confidence'].mean():.2f}%",
        len(mule_rings) if 'mule_rings' in dir() else 0
    ]
})

print("\n" + "="*50)
print("SUMMARY STATISTICS")
print("="*50)
print(summary_stats.to_string(index=False))

# Calculate silhouette scores for clustering models
if len(set(dbscan_labels)) > 1:
    dbscan_silhouette = silhouette_score(X_scaled, dbscan_labels)
    print(f"DBSCAN Silhouette Score: {dbscan_silhouette:.3f}")

if len(set(gmm_labels)) > 1:
    gmm_silhouette = silhouette_score(X_scaled, gmm_labels)
    print(f"GMM Silhouette Score: {gmm_silhouette:.3f}")

# Calculate Calinski-Harabasz Index
if len(set(dbscan_labels)) > 1:
    ch_score = calinski_harabasz_score(X_scaled, dbscan_labels)
    print(f"DBSCAN Calinski-Harabasz Score: {ch_score:.3f}")

# Calculate Davies-Bouldin Index
if len(set(dbscan_labels)) > 1:
    db_score = davies_bouldin_score(X_scaled, dbscan_labels)
    print(f"DBSCAN Davies-Bouldin Score: {db_score:.3f}")

# Model agreement matrix
model_columns = ['iso_forest_anomaly', 'dbscan_is_noise', 'gmm_anomaly', 'lof_anomaly']
agreement_matrix = account_features[model_columns].corr()

plt.figure(figsize=(8, 6))
sns.heatmap(agreement_matrix, annot=True, cmap='coolwarm', center=0,
            xticklabels=['Isolation Forest', 'DBSCAN', 'GMM', 'LOF'],
            yticklabels=['Isolation Forest', 'DBSCAN', 'GMM', 'LOF'])
plt.title('Model Agreement Correlation Matrix')
plt.tight_layout()
plt.show()